export const ADD_STAFF = 'ADD_STAFF';
export const STAFF_LOADING = 'STAFF_LOADING';
export const STAFF_FAILED = 'STAFF_FAILED';

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DEPARTMENT_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENT_FAILED = "DEPARTMENTS_FAILED";

export const ADD_STAFFSALARY = "ADD_STAFFSALARY";
export const STAFFSALARY_LOADING = "STAFFSALARY_LOADING";
export const STAFFSALARY_FAILED = "STAFFSALARY_FAILED";